#? Rules can be added here as most of the configuration are dynamic

# // █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# // ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Sizes for floating popups
windowrule = size 85% 95%

# Reglas para popups comunes
windowrule = float 1, match:tag common-popups
windowrule = size 60% 90%, match:tag common-popups

# Fix file chooser dialogs opening off-screen
windowrule = float 1, match:tag portal-dialogs
windowrule = center 1, match:tag portal-dialogs

# Only add the Core applications here
windowrule = float 1, match:class ^(com.gabm.satty)$

windowrule {
  name = float-dolphin-progress
  match:class = ^(org.kde.dolphin)$
  match:title = ^(Progress Dialog — Dolphin)$
  float = on
}

windowrule {
  name = float-dolphin-copy
  match:class = ^(org.kde.dolphin)$
  match:title = ^(Copying — Dolphin)$
  float = on
}

windowrule = float 1, match:title ^(About Mozilla Firefox)$
windowrule = float 1, match:initial_title ^(top)$
windowrule = float 1, match:initial_title ^(btop)$
windowrule = float 1, match:initial_title ^(htop)$
windowrule = float 1, match:class ^(vlc)$
windowrule = float 1, match:class ^(kvantummanager)$
windowrule = float 1, match:class ^(qt5ct)$
windowrule = float 1, match:class ^(qt6ct)$
windowrule = float 1, match:class ^(nwg-look)$
windowrule = float 1, match:class ^(nwg-displays)$
windowrule = float 1, match:class ^(org.kde.ark)$
windowrule = float 1, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float 1, match:class ^(blueman-manager)$
windowrule = float 1, match:class ^(nm-applet)$
windowrule = float 1, match:class ^(nm-connection-editor)$
windowrule = float 1, match:class ^(org.kde.polkit-kde-authentication-agent-1)$

# common popups
windowrule = tag +common-popups, match:initial_title ^(Open File)$
windowrule = tag +common-popups, match:title ^(Choose Files)$
windowrule = tag +common-popups, match:title ^(Save As)$
windowrule = tag +common-popups, match:title ^(Confirm to replace files)$
windowrule = tag +common-popups, match:title ^(File Operation Progress)$
windowrule = tag +common-popups, match:class ^([Xx]dg-desktop-portal-gtk)$
windowrule = tag +common-popups, match:title ^(Open)$
windowrule = tag +common-popups, match:title ^(Authentication Required)$
windowrule = tag +common-popups, match:title ^(Add Folder to Workspace)$
windowrule = tag +common-popups, match:title ^(File Upload)(.*)$
windowrule = tag +common-popups, match:title ^(Choose wallpaper)(.*)$
windowrule = tag +common-popups, match:title ^(Library)(.*)$
windowrule = tag +common-popups, match:class ^(.*dialog.*)$
windowrule = tag +common-popups, match:title ^(.*dialog.*)$

# portal-dialogs
windowrule = tag +portal-dialogs, match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$
windowrule = tag +portal-dialogs, match:class ^(org.freedesktop.impl.portal.desktop.gtk)$
windowrule = tag +portal-dialogs, match:class ^([Xx]dg-desktop-portal-gtk)$


